version: 0.2
phases:
  install:
    commands:
      - apk add --no-cache curl wget
      - echo "----install & config kubectl---"
      - wget https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl
      - mv kubectl /usr/local/bin/kubectl
      - chmod +x /usr/local/bin/kubectl
      - aws eks --region $REGION update-kubeconfig --name $CLUSTER
  build:
    commands:
      - echo "----update deployment----"
      - sed -i "s/IMAGE_TAG/$CODEBUILD_RESOLVED_SOURCE_VERSION/g" deploy.yml
      - sed -i "s/LAST_RELOAD_DATE/$(date '+%Y%m%d-%H%M%S')/g" deploy.yml
      - kubectl apply -f deploy.yml
      - kubectl wait --for=condition=ready pod -l app=cb-ci-test
      - echo "----done----"
