version: '2'
services:
  web:
    image: $IMAGE_REPO_NAME
    build: ./web/
    container_name: web
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "database"
    depends_on:
      - database
  database:
    build: ./mysql/
    container_name: database
    environment:
        MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
      - "33060:33060"
