name: Backlog Notify

on: push

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Backlog Notify
        uses: bicstone/backlog-notify@master
        env:
          PROJECT_KEY: TESTPROJECT1
          API_HOST: githook.backlog.com
          API_KEY: ${{ secrets.BACKLOG_API_KEY }}
